### ISSUE TITLE
RC versions should be marked as pre-releases

### ISSUE THREAD

**Issue by mkevenaar** [fdm-monster/MonsterPi#48]
#### MonsterPi version

Version: NA

#### What were you doing?

Setting up documentation automation.

1. Go to https://github.com/fdm-monster/monsterpi/releases/latest

#### What did you expect to happen

See the latest stable release 

#### What happened instead?

The latest RC 

#### Additional context (optional)

This can be achieved by checking the pre-release checkbox when doing a release

**Comment by davidzwa** [comment]
Assigning myself on this one! Thx, good find!
